# For running the production Node app

FROM    node:7
ENV     NODE_ENV=production
EXPOSE  3000
WORKDIR /app
COPY    yarn.lock package.json /app/
RUN     yarn install
COPY    . /app
RUN     yarn run build
CMD     ["yarn", "run", "start"]