#!/bin/bash
set -euo pipefail

export AWS_DEFAULT_REGION=us-east-1

cluster="site-test"
task_family="buildkite-site"
service_name="${task_family}"
image="${ECR_REPOSITORY}:${BUILDKITE_BUILD_NUMBER}"

## This is the template definition of your containers
task_definition=$(cat << JSON
[{
  "image": "${image}",
  "logConfiguration": {
      "logDriver": "awslogs",
      "options": {
          "awslogs-group": "ecs-site-test",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "${service_name}"
      }
  },
  "portMappings": [{
    "containerPort": 3000,
    "protocol": "tcp"
  }],
  "memoryReservation": 128,
  "name": "site"
}]
JSON
)

## This is the revision of the task definition that gets created on each build
echo "--- :ecs: Registering new task definition for ${task_family}"
task_revision=$(
  aws ecs register-task-definition \
    --family "${task_family}" \
    --container-definitions "$task_definition" \
    | jq '.taskDefinition.revision')

## This updates the service with the created revision
echo "--- :ecs: Updating service for ${service_name}"
aws ecs update-service \
  --cluster "${cluster}" \
  --service "${service_name}" \
  --task-definition "${task_family}:${task_revision}"

## Now we wait till it's stable
echo "--- :ecs: Waiting for services to stabilize"
aws ecs wait services-stable \
  --cluster "${cluster}" \
  --services "${service_name}"

aws ecs describe-services \
  --cluster "${cluster}" \
  --service "${service_name}"

echo "+++ :ecs: Service is up! 🚀"
