#!/bin/sh

set -euo pipefail

echo "~~~ :node: Installing nsp"

# Install https://github.com/nodesecurity/nsp
npm install -q -g nsp

echo "+++ 🔐 Running nsp security checks"

# Check deps against known package vulnerabilities
nsp check
