#!/bin/bash

# Creates a percy snapshot and annotates the Buildkite build with a handy link
# to the Percy build using the output from the Percy command
#
# Designed to be run inside the percy container via Docker Compose, ie:
#
#   docker-compose -f docker-compose.percy.yml run percy

set -euo pipefail

echo "Creating Percy snapshot"

PERCY_OUTPUT=$(percy --trace snapshot .)
echo "${PERCY_OUTPUT}"

PERCY_BUILD_LINK=$(echo "${PERCY_OUTPUT}" | grep -o 'http[^ ]*')

if [[ "${BUILDKITE_JOB_ID:-}" != "" && "${PERCY_BUILD_LINK}" != "" ]]; then
  ANNOTATION=":percy: View the [Percy Visual Diff](${PERCY_BUILD_LINK})"
  buildkite-agent annotate --style success --context percy "${ANNOTATION}"
else
  echo "Skipping buildkite-agent annotate"
fi
