#!/bin/sh
set -euo pipefail

echo "~~~ :node: Installing retire"

# Install https://github.com/RetireJS/retire.js
yarn global add retire

echo "+++ 🔐 Running retire security checks"

# Check JS libraries against known vulnerabilities
retire

echo "✅ Looks AOK"
